### ISSUE TITLE
[BUG] Personal PD vehicles public parking 

### ISSUE THREAD

**Issue by Petrovic247** [ParadoxGamingRP/paradox-bugs#562]
### Your Discord Name

Pretenderpatrol#5993

### A clear and concise description of what the bug is

For a little while PD has been only able to park their Personal CVPI at a public safety garage. You also must be ON duty to park or take out. If you go to a public garage you are unable to park vehicle. 

### Steps to Reproduce the Bug

Tried myself 
Had Brasciole try, same result. 
Multiple reports from Officers. 

### Expected Behavior

Able to park Personal CVPI at any parking garage. 

### Screenshots/Videos

N/a

### Extra Notes (Optional)

Am currently on LOA and do not have computer.

**Comment by Sly-Panda** [comment]
It is intended that you can only park your personal vehicles in a public safety garage and this has always been the case since the inception of personal vehicle purchases. As it's a public work vehicle it makes sense that you have to be on duty to take out/park it as well as it's a public safety vehicle.

**Comment by xXJamieXx** [comment]
Fixed next restart.
